name: currency_rates

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: 1.0.5
  dio: 5.2.1+1
  drift: 2.15.0
  easy_localization: 3.0.2
  easy_localization_loader: 1.0.1+1
  envied: 0.5.3
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_screenutil: 5.8.4
  flutter_svg: 2.0.7
  freezed_annotation: 2.2.0
  get_it: 7.6.0
  go_router: 9.0.1
  injectable: 2.1.2
  json_annotation: 4.8.1
  logger: 1.4.0
  path: 1.8.3
  path_provider: 2.1.2
  resource_repository: 0.0.4
  retrofit: 4.0.1
  rxdart: 0.27.7
  sqlite3_flutter_libs: 0.5.0

dev_dependencies:
  build_runner: 2.4.8
  drift_dev: 2.15.0
  envied_generator: 0.5.3
  flutter_gen_runner: 5.3.1
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.3.5
  go_router_builder: 2.2.0
  injectable_generator: 2.1.6
  json_serializable: 6.7.1
  retrofit_generator: 7.0.8

flutter_gen:
  output: lib/generated/
  line_length: 120
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
